### PR TITLE
chore: Bump asciinema player librairy

### PR DESCRIPTION
**Pull request by benjaminParisel**
* retrieve asciinema from npm
* Upgrade asciinema to version 3.0.0

Close https://github.com/bonitasoft/bonita-documentation-site/issues/352

### CODE REVIEW

**Review by tbouffard — COMMENTED** [review]
I have noticed that the height of the asciinema window is smaller than before.
I don't know if the previous css had been customized directly in the min file or in our theme, or if this change is introduced by the asciinema lib itself

before | now
---- | ----
image | image

**Comment by tbouffard** [comment]
⚠️ When I load the asciinema preview page, the console displays the following logs (from Chrome, I see quite similar logs with Firefox)
```
libs.js:5 player mounted
libs.js:5 containerW = 616
DevTools failed to load source map: Could not load content for https://bonitasoft-bonita-documentation-theme-build_preview-pr-104.surge.sh/_/js/vendor/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by benjaminParisel** [comment]
libs.js:5 player mounted https://github.com/asciinema/asciinema-player/blob/328239caa7ab18d82e5a07ec85e125da807a562c/src/components/Player.js#L112
libs.js:5 containerW = 616 https://github.com/asciinema/asciinema-player/blob/328239caa7ab18d82e5a07ec85e125da807a562c/src/components/Player.js#L173
this logs is in source code of asciinema library.

**Comment by tbouffard** [comment]
Thx for the information, about the sourcemap, yes this is not related to this PR, I didn't notice it before.
I guess this comes from a misconfiguration or that we don't deploy sourcemaps files: https://github.com/bonitasoft/bonita-documentation-theme/blob/64d9d15c81c1a7942203627fa5b893fb3751faf6/gulp.d/tasks/build.js#L26
Let's manage it later.

**Review by tbouffard — APPROVED** [review]
Nice, 42a1932 restores the size we previously used.
See https://github.com/asciinema/asciinema-player/tree/v3.0.0#fit

**Pull request merged**
