### PR TITLE
fix: Make nav bar over message block

### PR DESCRIPTION
**Pull request by jeromecambon**
Covers https://github.com/bonitasoft/bonita-documentation-theme/issues/121

### CODE REVIEW

**Review by tbouffard — CHANGES_REQUESTED** [review]
✔️ the toolbar is now on top
❌ when clicking on the arrow, the toolbar doesn't hide anymore

Here is how it behaves in the current `master` branch (the file name of the videos provided here are wrong)

https://user-images.githubusercontent.com/27200110/208075825-1373151f-950b-4a52-a8f7-b41678641990.mp4

And in the PR preview

https://user-images.githubusercontent.com/27200110/208075831-47fff43b-be7d-42f4-9fc1-4af5dc87fd48.mp4

**Comment by tbouffard** [comment]
> Since the issue is only for mobile (or very small window) and very specific versions, I suggest we keep the current behavior (i.e. without this fix) for now.

The PR improves things so we could merge as it is provided here. If so, I will open an issue about the arrow not working anymore. We cannot silent problems like this one just because it is hard to fix.

**Comment by jeromecambon** [comment]
> 



> > Since the issue is only for mobile (or very small window) and very specific versions, I suggest we keep the current behavior (i.e. without this fix) for now.
> 
> The PR improves things so we could merge as it is provided here. If so, I will open an issue about the arrow not working anymore. We cannot silent problems like this one just because it is hard to fix.

I don't have a strong opinion on this. The fix improves things on one side but may also have unwanted side effects. But let's push it.

**Review by benjaminParisel — APPROVED** [review]

**Comment by tbouffard** [comment]
See issue #167 about the back button not working anymore

**Pull request merged**
